### ISSUE TITLE
setuptool in version 72.0.0 removed test command

### ISSUE THREAD

**Issue by johniak** [saxix/django-admin-extra-buttons#22]
https://setuptools.pypa.io/en/stable/history.html#v72-0-0
https://github.com/saxix/django-admin-extra-buttons/blob/develop/setup.py#L9

**Comment by tobiasgardner** [comment]
Just confirming, breaks our builds in the pipeline for us.

Installing dependencies from [Pipfile.lock](https://bitbucket.org/eComBooster/ecombooster/src/60f607e3707b55926f4db9b9bf0d20deb4dfb4b6/Pipfile.lock) (3f8884)...
[pipenv.exceptions.InstallError]: Collecting amqp==5.2.0 (from -r /tmp/pipenv-5_gcfwz6-requirements/pipenv-zqvc_q9p-hashed-reqs.txt (line 1))
...
[pipenv.exceptions.InstallError]: Collecting django==4.1.13 (from -r /tmp/pipenv-5_gcfwz6-requirements/pipenv-zqvc_q9p-hashed-reqs.txt (line 37))
[pipenv.exceptions.InstallError]:   Downloading Django-4.1.13-py3-none-any.whl (8.1 MB)
[pipenv.exceptions.InstallError]: Collecting django-admin-extra-buttons==1.5.8 (from -r /tmp/pipenv-5_gcfwz6-requirements/pipenv-zqvc_q9p-hashed-reqs.txt (line 38))
[pipenv.exceptions.InstallError]:   Downloading django_admin_extra_buttons-1.5.8.tar.gz (995 kB)
[pipenv.exceptions.InstallError]:   Installing build dependencies: started
[pipenv.exceptions.InstallError]:   Installing build dependencies: finished with status 'done'
[pipenv.exceptions.InstallError]:   Getting requirements to build wheel: started
[pipenv.exceptions.InstallError]:   Getting requirements to build wheel: finished with status 'error'
[pipenv.exceptions.InstallError]: error: subprocess-exited-with-error
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:   × Getting requirements to build wheel did not run successfully.
[pipenv.exceptions.InstallError]:   │ exit code: 1
[pipenv.exceptions.InstallError]:   ╰─> [20 lines of output]
[pipenv.exceptions.InstallError]:       Traceback (most recent call last):
[pipenv.exceptions.InstallError]:         File "/usr/local/lib/python3.12/site-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
[pipenv.exceptions.InstallError]:           main()
[pipenv.exceptions.InstallError]:         File "/usr/local/lib/python3.12/site-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
[pipenv.exceptions.InstallError]:           json_out['return_val'] = hook(**hook_input['kwargs'])
[pipenv.exceptions.InstallError]:                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pipenv.exceptions.InstallError]:         File "/usr/local/lib/python3.12/site-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
[pipenv.exceptions.InstallError]:           return hook(config_settings)
[pipenv.exceptions.InstallError]:                  ^^^^^^^^^^^^^^^^^^^^^
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-mftznnig/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
[pipenv.exceptions.InstallError]:           return self._get_build_requires(config_settings, requirements=[])
[pipenv.exceptions.InstallError]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-mftznnig/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
[pipenv.exceptions.InstallError]:           self.run_setup()
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-mftznnig/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
[pipenv.exceptions.InstallError]:           super().run_setup(setup_script=setup_script)
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-mftznnig/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
[pipenv.exceptions.InstallError]:           exec(code, locals())
[pipenv.exceptions.InstallError]:         File "<string>", line 9, in <module>
[pipenv.exceptions.InstallError]:       ModuleNotFoundError: No module named 'setuptools.command.test'
[pipenv.exceptions.InstallError]:       [end of output]
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.
[pipenv.exceptions.InstallError]: error: subprocess-exited-with-error
[pipenv.exceptions.InstallError]: 
[pipenv.exceptions.InstallError]: × Getting requirements to build wheel did not run successfully.
[pipenv.exceptions.InstallError]: │ exit code: 1
[pipenv.exceptions.InstallError]: ╰─> See above for output.
[pipenv.exceptions.InstallError]: 
[pipenv.exceptions.InstallError]: note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Couldn't install package: {}
 Package installation failed...

**Comment by alexgmin** [comment]
The import is also not needed since there's no use of `TestCommand`

**Comment by Will-Hoey** [comment]
Release 72.0 was yanked. This should no longer be an issue https://pypi.org/project/setuptools/#history

**Comment by alexgmin** [comment]
The import is still not needed, but is not an urgent issue anymore. And ideally the package shouldn't use `setup.py`.
